### ISSUE TITLE
ILLIXR_INTEGRATION build failing on aarch64

### ISSUE THREAD

**Issue by brajskular** [ILLIXR/open_vins#20]
Building open_vins on a Jetson nano - aarch64. The standalone version builds successfully, while the illixr integration build fails with the error:
> 
> [ 65%] Building CXX object ov_msckf/CMakeFiles/ov_msckf_lib.dir/src/state/State.cpp.o
> In file included from /home/brajskular/open_vins/ov_msckf/src/sim/Simulator.cpp:21:
> In file included from /home/brajskular/open_vins/ov_msckf/src/sim/Simulator.h:38:
> In file included from /home/brajskular/open_vins/ov_msckf/src/core/VioManagerOptions.h:30:
> /home/brajskular/open_vins/ov_msckf/src/state/Propagator.h:29:10: fatal error: 'common/data_format.hpp' file not found
> #include "common/data_format.hpp"
>          ^~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ov_msckf/CMakeFiles/ov_msckf_lib.dir/build.make:75: recipe for target 'ov_msckf/CMakeFiles/ov_msckf_lib.dir/src/sim/Simulator.cpp.o' failed
> make[3]: *** [ov_msckf/CMakeFiles/ov_msckf_lib.dir/src/sim/Simulator.cpp.o] Error 1
> make[3]: *** Waiting for unfinished jobs....
> make[3]: Leaving directory '/home/brajskular/open_vins/build/RelWithDebInfo'
> CMakeFiles/Makefile2:143: recipe for target 'ov_msckf/CMakeFiles/ov_msckf_lib.dir/all' failed
> make[2]: *** [ov_msckf/CMakeFiles/ov_msckf_lib.dir/all] Error 2
> make[2]: Leaving directory '/home/brajskular/open_vins/build/RelWithDebInfo'
> Makefile:90: recipe for target 'all' failed

The issue is not seen on x86 architecture, and is specific to aarch64.

To recreate:
ILLIXR_INTEGRATION=yes make opt

**Comment by shg8** [comment]
Hello, it seems like that you're compiling this repo by itself without ILLIXR. If you have changes made in OpenVins, have you tried modifying that path [here](https://github.com/ILLIXR/ILLIXR/blob/e17e6c5679822a4f021d0a6f85628b5ab698b384/configs/rt_slam_plugins.yaml#L12) in our build system?

**Comment by jianxiapyh** [comment]
Hi @brajskular, Is this still a problem or should we close the issue?

**Comment by brajskular** [comment]
Yup, building with ILLIXR resolves the issue. Thank you!
